services:
  web:
    image: "caiansantana/flask-api:latest"
    ports:
      - "${FLASK_PORT}:5000" 
    networks:
      - app
    environment:
      - FLASK_ENV=production 
      - DATABASE_URI=mysql+mysqlconnector://${DB_USER}:${DB_PASS}@mysql/${DB_NAME}
    depends_on:
      mysql:
          condition: service_healthy

  mysql:
    image: "mysql:oraclelinux9"
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:

networks:
  app:
    driver: bridge